import crypto from "node:crypto";
import fs from "node:fs";

const expectedHash = "6a0442d9156d99dbf7471ba5aa08f1428b7b3746d25f57df6c2a2beeb212ab28";
const projectAddress = "0x043F8e52461165BEfe5b8fE66F1de8F4F0C92C35";
const documentedRuntimeAddresses = new Set([
  projectAddress,
  "0x3065E31B1D993d7C0D59E6786844cBa56780B2d3",
  "0x5a52d040581A76e2C032542855D31480f2ea7097",
].map((address) => address.toLowerCase()));

function read(path) {
  return fs.readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

function fail(message) {
  console.error(`FAIL: ${message}`);
  process.exitCode = 1;
}

const sourceBytes = fs.readFileSync(new URL("../contract/AccedeLedger.py", import.meta.url));
const actualHash = crypto.createHash("sha256").update(sourceBytes).digest("hex");
if (actualHash !== expectedHash) fail(`contract parity ${actualHash}`);

const source = sourceBytes.toString("utf8");
for (const method of [
  "open_undertaking",
  "accede",
  "decline",
  "record_performance",
  "contest",
  "get_undertaking",
  "get_performances",
  "get_contest_note",
  "get_limits",
]) {
  if (!source.includes(`def ${method}(`)) fail(`missing contract method ${method}`);
}
if (!source.includes('"contract_name": "OutsideDutyBind"')) fail("internal contract identity changed");

const config = read("src/lib/config.ts");
if (!config.includes(projectAddress)) fail("Project address is not the default config");

const publicFiles = [
  "README.md",
  "TESTING.md",
  "SUBMISSION_NOTE.md",
  "src/App.tsx",
  "src/lib/config.ts",
  "src/lib/genlayer.ts",
].map(read).join("\n");

const addresses = publicFiles.match(/0x[0-9a-fA-F]{40}(?![0-9a-fA-F])/g) ?? [];
for (const address of addresses) {
  if (!documentedRuntimeAddresses.has(address.toLowerCase())) {
    fail(`stale address in public Project files: ${address}`);
  }
}
if (/generated by|assistant attribution/i.test(publicFiles)) fail("generated attribution in public files");

if (process.exitCode) process.exit(process.exitCode);
console.log(`PASS Project source parity ${actualHash}`);
console.log(`PASS Project address isolation ${projectAddress}`);
console.log("PASS public-file address and attribution scan");
